### ISSUE TITLE
Screen resolution

### ISSUE THREAD

**Issue by GGutss** [WMCB-Tech/termux-wayland#43]
How to change resolution?  I'm using a tablet with a resolution of 1200×1920, letters end up getting small.

**Comment by suhan-paradkar** [comment]
You can change that in screen resolution settings in XFCE and adjust custom DPI

**Comment by GGutss** [comment]
I was testing the box86 to run some visual novels, but because of the tablet high resolution, the game window gets small, and if increase the game window, it loses performance, so I wanted to know if there's a way to decrease the resolution, just like it does on vnc.
