### ISSUE TITLE
Right click 

### ISSUE THREAD

**Issue by Yisus7u7** [WMCB-Tech/termux-wayland#9]
Currently the right click is compatible with "simulated touchpad" and the xfce4 desktop, this should be by xfce4 and not the app, but please add a right click option.

![Screenshot_20210708-145445](https://user-images.githubusercontent.com/64093255/125176634-9f5fc900-e19a-11eb-9672-2208cc06eaa8.png)

**Comment by suhan-paradkar** [comment]
It will require some minor changes to the code.. will do so soon

**Comment by Heasterian** [comment]
Probably option to assign physical keys to mouse functions in touchpad mode would also be great idea.

**Comment by suhan-paradkar** [comment]
Please open this issue upstream... It will be fixed there...
